name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install SDL2
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev libsdl2-ttf-dev
    - name: Build
      run: |
        rustc --version
        cargo build
    - name: Tests
      run: cargo test

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install SDL2
      run: |
        brew install sdl2
        brew install sdl2_ttf
        brew install rustup
        rustup-init -y --default-toolchain stable
    - name: Build
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        rustc --version
        cargo build
    - name: Test
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        cargo test
